### ISSUE TITLE
No associated proxy found in cache. Terminating connection

### ISSUE THREAD

**Issue by Uri-Katsir** [trek10inc/aws-lambda-debugger#1]
Hello,

Configured the debugger but when running in Chrome, I see the following error.

![image](https://user-images.githubusercontent.com/24898727/30598202-2a98a580-9d27-11e7-8abe-71295e3a4954.png)

**Comment by azurelogic** [comment]
Hi @Uri-Katsir,

It looks like you are trying to connect without having run a correctly configured Lambda function first. Just like any other debugger attachment, the target process needs to be running first in order to connect.

Things to check:
- Did you install the npm package and put `require('aws-lambda-debugger')` at the end of the file containing the handler you wish to debug?
- Did you add the required environment variables?
- Did you execute the Lambda function before attempting to attach the debugger? (note: You will see a log message when the Lambda proxy connects to the broker)

Relevant documentation: ["Use it!"](https://github.com/trek10inc/aws-lambda-debugger#use-it)

Let me know if this helps resolve your issue. Also, if that helps, feel free to give some feedback on how we can improve the docs if needed.

Thanks!
